#!/bin/bash
echo "Lets install some shit"

curl -LOk https://github.com/dwkns/system-install/archive/master.zip
unzip master.zip 

if [ $? -eq 0 ]; then
    rm master.zip
    echo "---- Download succeded ----"
    echo "cd into system-install-master and run ./install-script.sh"

else
    echo "---- Couldn't download the installer files. ----"
    echo "---- Check to see if a folder named 'system-install-master' already exists."
    echo "---- Delete it and try again."
fi
